#!/usr/bin/env bash
set -e

echo "Secret encryption"

confluent secret file encrypt --config-file ./kafka/server.properties \
    --local-secrets-file ./kafka/security.properties \
    --remote-secrets-file /etc/kafka/security.properties \
    --config "listener.name.sasl_plaintext.scram-sha-256.sasl.jaas.config"

echo "Docker containers start"
docker-compose up -d --build kafka

docker-compose exec zookeeper  kafka-configs --zookeeper zookeeper:2181 --alter --add-config 'SCRAM-SHA-256=[iterations=8192,password=kafka-secret]' --entity-type users --entity-name kafka

echo "Example configuration:"
echo "Should succeed (kafka is a super user)"
echo "-> docker-compose exec kafka kafka-console-producer --broker-list kafka:9092 --topic test-topic --producer.config=/etc/kafka/kafka.properties"
echo "-> docker-compose exec kafka kafka-console-consumer --bootstrap-server kafka:9092 --topic test-topic --consumer.config=/etc/kafka/kafka.properties --from-beginning"
