#!/usr/bin/env bash
set -e

echo "Secret encryption"

confluent secret file encrypt --config-file ./kafka-connect/kafka-connect.properties \
  --local-secrets-file ./kafka-connect/security.properties \
  --remote-secrets-file /etc/kafka-connect/security.properties \
  --config "config.storage.topic"

confluent secret file encrypt --config-file ./kafka/server.properties \
    --local-secrets-file ./kafka/security.properties \
    --remote-secrets-file /etc/kafka/security.properties \
    --config "listener.name.sasl_plaintext.scram-sha-256.sasl.jaas.config"

echo "Docker containers start"
docker-compose up -d --build zookeeper


# docker-compose exec kafka kafka-configs --zookeeper zookeeper:2181 --alter --add-config 'SCRAM-SHA-256=[password=kafka],SCRAM-SHA-512=[password=kafka]' --entity-type users --entity-name kafka

docker-compose exec zookeeper  kafka-configs --zookeeper zookeeper:2181 --alter --add-config 'SCRAM-SHA-256=[iterations=8192,password=kafka-secret]' --entity-type users --entity-name kafka

docker-compose up -d --build kafka

echo "Example configuration:"
echo "Should succeed (kafka is a super user)"
echo "-> docker-compose exec kafka kafka-console-producer --broker-list kafka:9092 --topic test-topic --producer.config=/etc/kafka/kafka.properties"



#confluent secret file decrypt \
#--local-secrets-file ./connect/security.properties \
#--config-file ./connect/kafka-connect.properties \
#--output-file decrypt.txt
